test-commit

diff --git a/.github/workflows/02-ci.yml b/.github/workflows/02-ci.yml
--- a/.github/workflows/02-ci.yml
+++ b/.github/workflows/02-ci.yml
@@ -31,3 +31,12 @@ jobs:
       - name: Run tests
         # This is the key verification step in the CI Workflow.
         run: python -m unittest discover -s tests -v
+      - name: Verify Python
+        run: puthon
+      - name: Verify Python version
+        run: python --version
+
+      - name: Verify files exist
+        run: |
+          echo "Checking app directory..."
+          ls -la app || echo "app folder not found"
